name: CI (Self-Hosted)

on:
  push:
    branches: ["main", "feature/**"]

  workflow_dispatch:

jobs:
  run-local:
    runs-on: [self-hosted, windows]

    steps:
      - name: 1. Завантаження коду
        uses: actions/checkout@v4

      - name: 2. Перевірка середовища
        run: |
          python --version
          echo "Робоча директорія: %CD%"

      - name: 3. Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas matplotlib seaborn simpy

      - name: 4. Підготовка папок та запуск
        shell: cmd
        env:
          USE_LOCAL_DATA: "true"
        run: |
          if not exist "artifacts\visualization" mkdir "artifacts\visualization"
          if not exist "reports\figures" mkdir "reports\figures"
          
          echo [LOCAL] Запускаємо візуалізацію з великим файлом...
          python src\visualization.py > artifacts\visualization\run.log 2>&1

      - name: 5. Збереження результатів (Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: local-pc-result
          path: |
            artifacts/visualization/
            reports/figures/
          if-no-files-found: ignore