name: CI (Self-Hosted)

on:
  workflow_dispatch:

jobs:
  run-local:

    runs-on: [self-hosted, windows]

    steps:
      - name: 1. Завантаження коду
        uses: actions/checkout@v4

      - name: 2. Перевірка середовища
        run: |
          python --version
          echo "Робоча директорія: %CD%"

      - name: 3. Встановлення залежностей
        run: python -m pip install pandas matplotlib seaborn simpy

      - name: 4. Робота з локальним датасетом та запуск
        shell: cmd
        run: |

          python src\visualization.py > artifacts\visualization\run.log 2>&1 || (type artifacts\visualization\run.log & exit 1)

      - name: 5. Збереження результатів (Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: local-pc-result
          path: |
            artifacts/visualization/
            reports/figures/
          if-no-files-found: ignore