name: CI (Cloud Pipeline)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      module:
        description: "Оберіть модуль (або 'all')"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - data_load
          - data_quality_analysis
          - data_research
          - visualization

jobs:
  run-modules:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module: [data_load, data_quality_analysis, data_research, visualization]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn simpy

      - name: Run module
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.module == 'all' || github.event.inputs.module == matrix.module }}
        run: |
          mkdir -p artifacts/${{ matrix.module }}
          echo "Запускаємо скрипт src/${{ matrix.module }}.py..."
          
          python src/${{ matrix.module }}.py > artifacts/${{ matrix.module }}/run.log 2>&1 || (cat artifacts/${{ matrix.module }}/run.log && exit 1)

      - name: Upload artifacts
        if: ${{ always() && (github.event_name != 'workflow_dispatch' || github.event.inputs.module == 'all' || github.event.inputs.module == matrix.module) }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.module }}
          path: |
            artifacts/${{ matrix.module }}/
            reports/figures/
          if-no-files-found: ignore